fix: fixing issue 1839
aws/aws-sdk-net pull request #1937
Opened 2021-11-15 13:31 UTC by MDanialSaleem

converts eager loading of loggers to lazy loading.

## Description
The Logger class always loads all the loggers in its constructor and then enables one of them depending on the value in the ```AWSConfigs.LoggingConfig.LogTo```. This eager loading is unnecessary. This PR fixes that by making the loading lazy. Now, we only load a logger when it is specified for the first time in ```AWSConfigs.LoggingConfig.LogTo```.

## Motivation and Context
fixes [issue 1839](https://github.com/aws/aws-sdk-net/issues/1839)

## Testing
- follow instructions [here](https://github.com/MDanialSaleem/aws-sdk-net#modularization) to build the project, it will generate appropriate dlls.
- use the code provided [here](https://github.com/aws/aws-sdk-net/issues/1839) . instead of adding the awssdk package from nuget, just reference the dlls generated at ``` aws-sdk-net-master\sdk\src\Services\S3\bin\Debug\{your runtime}\ ```
- I have run this against unit tests

## Screenshots (if appropriate)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] My code follows the code style of this project  (not sure, couldn't find any doc, happy to refactor to conform)
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed (only checked against unit tests)

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-02-09 02:13 UTC, normj approved these changes

2023-02-09 03:25 UTC, boblodgett commented on sdk/src/Core/Amazon.Runtime/Internal/Util/Logger.cs
> +            bool found = true;
Shouldn't this be `bool found = false`? There is no way for found to be false currently.

2023-02-09 06:27 UTC, normj requested changes

2023-02-09 06:27 UTC, normj commented on sdk/src/Core/Amazon.Runtime/Internal/Util/Logger.cs
>              foreach (InternalLogger il in loggers)
Since the `loggers` collection is no longer being filled in during the constructor this `foreach` loop never going to be entered.

2023-02-09 06:27 UTC, normj commented on sdk/src/Core/Amazon.Runtime/Internal/Util/Logger.cs
> +                    il.IsEnabled = true;
With this code `IsEnabled` is always being set to true but the this method is called if the logging configuration changes which might disable a logger.

2023-03-22 18:44 UTC, ashishdhingra commented
@MDanialSaleem Please review comments above and help address them for this PR.

Thanks,
Ashish

2023-04-19 21:34 UTC, ashishdhingra commented
Closing PR due to lack of activity.

2023-04-19 21:34 UTC, closed without merging