Handling conversions of null entries of DynamoDBEntry to nullable types and improving exception for non-nullable types
aws/aws-sdk-net pull request #1947
Opened 2021-12-06 02:44 UTC by diegorafael

Fixing null reference exception when attempting implicitly convert a null DynamoDBEntry to string;
Improving exception message when explicitly attempting to convert a null DynamoDBEntry to non-nullable types;
Avoiding NullReferenceException when trying to convert a null DynamoDBEntry.

## Description
The implicit and explicit conversion from DynanoDBEntry methods were adjusted to handle properly conversions to `null` using the null propagator. In the cases that null entry is not expected, I'm throwing an `InvalidOperationException` instead of a generic NullReferenceException.

## Motivation and Context

In some cases use cases of DynamoDB we have instances of Document that doesn't contain all properties handled by the equivalent class model. Such cases enforce the `Document` -> `<class model>` mapping method to deal with checks for containing the key (`document.ContaisKey(key)`) to avoid a NullReferenceException thrown by the implicit conversion method for every property on the `<class model>`. 

This new approach lets the user deal with null property values in their own time and makes the problem clearer when it's not permitted.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-09-13 21:28 UTC, ashovlin commented
Sorry about delay getting to this. We have a new internal process to revisit PRs more methodically, so taking a look now.

I agree that throwing `InvalidOperationException` with specific messages (or possibly an `ArgumentNullException`) is an improvement over `NullReferenceException`. 

However we're cautious around changing the exceptions that are thrown from the SDK because users may be catching the `NullReferenceException` currently.

```
var document = new Document();

document.TryGetValue("DoesNotExist", out DynamoDBEntry entry);

// Case 1 - Value Types
// Before: throws NullReferenceException
// After: throws InvalidOperationException
var value = (bool)entry;

// Case 2 - Reference Types & Collections
// Before: throws NullReferenceException
// After: "value" is null
var value = (byte[])entry;

// If somebody has something like this, it'll behave differently upon upgrade
try 
{
    document.TryGetValue("MayNotExist", out DynamoDBEntry entry);
    var value = (bool)entry;
    
    // do something with value
} 
catch (NullReferenceException ex)
{
    // do something else
}
```

A new major version of the high-level DynamoDB on our radar, I'll note that we may want to improve these exceptions and null handling.

Some strategies we may apply in the current major version:
* Only throwing new/different exceptions if the user opts in via some new configuration option. 
    * Not sure if that is worth it here, and these objects can exist outside of a `Table` where we generally allow configuration.
* Still throwing the original exception type, but with an custom message. 
    * However `throw new NullReferenceException("<improved message>");` triggers https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201
* We could subclass NRE (`public class DynamoDBNullReferenceException : NullReferenceException`), that would allow us to improve the message but still let existing `catch` statements handle it.
    * Though don't see a precedent for this yet in the SDK. Curious what @normj thinks of this approach.
    
 Since some time has passed, is this still an issue for you? I think we'd have to weigh the impact vs. one of the workarounds that's safe to do in the current version.

2023-09-13 22:09 UTC, diegorafael commented
> Sorry about delay getting to this. We have a new internal process to revisit PRs more methodically, so taking a look now.
> 
> I agree that throwing `InvalidOperationException` with specific messages (or possibly an `ArgumentNullException`) is an improvement over `NullReferenceException`.
> 
> However we're cautious around changing the exceptions that are thrown from the SDK because users may be catching the `NullReferenceException` currently.
> 
> ```
> var document = new Document();
> 
> document.TryGetValue("DoesNotExist", out DynamoDBEntry entry);
> 
> // Case 1 - Value Types
> // Before: throws NullReferenceException
> // After: throws InvalidOperationException
> var value = (bool)entry;
> 
> // Case 2 - Reference Types & Collections
> // Before: throws NullReferenceException
> // After: "value" is null
> var value = (byte[])entry;
> 
> // If somebody has something like this, it'll behave differently upon upgrade
> try 
> {
>     document.TryGetValue("MayNotExist", out DynamoDBEntry entry);
>     var value = (bool)entry;
>     
>     // do something with value
> } 
> catch (NullReferenceException ex)
> {
>     // do something else
> }
> ```
> 
> A new major version of the high-level DynamoDB on our radar, I'll note that we may want to improve these exceptions and null handling.
> 
> Some strategies we may apply in the current major version:
> 
> * Only throwing new/different exceptions if the user opts in via some new configuration option.
>   
>   * Not sure if that is worth it here, and these objects can exist outside of a `Table` where we generally allow configuration.
> * Still throwing the original exception type, but with an custom message.
>   
>   * However `throw new NullReferenceException("<improved message>");` triggers https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2201
> * We could subclass NRE (`public class DynamoDBNullReferenceException : NullReferenceException`), that would allow us to improve the message but still let existing `catch` statements handle it.
>   
>   * Though don't see a precedent for this yet in the SDK. Curious what @normj thinks of this approach.
> 
> Since some time has passed, is this still an issue for you? I think we'd have to weigh the impact vs. one of the workarounds that's safe to do in the current version.

Better late than never 😄 

Its not a problem anymore, the motivation here was to save some time for other users that could face the same problem that took out around 2 days from 3 devs just trying figure out an issue in the wrong place 🤣.

Completely understand the concern, but I disagree that in this case it would harm the experience of using the lib. That is my thoughts:

- The current version is not explicitly throwing `NullReferenceException`, and it is being raised by an "inconsistent" input from client app side, so any eventual handling on that would be strongly related to workarounds on the client app as well.
- If promoted, these changes would affect newer versions of the SDK only. So if any client app run into that scenario, it would be for a "live" app, considering it is upgrading packages, instead of a legacy one.
- An eventual occurrence of break on exception handlings this time would explicitly tells the user the specific problem, instead of  a mysterious null pointer hidden somewhere, making it easy to fix

Other than that, I think the option of use a feature flag to enable the new behavior of throwing the exception sound like the only feasible to get the best of both sides.

2023-09-19 18:03 UTC, boblodgett requested changes
We discussed this as a team and will accept the change to `InvalidOperationException` with a better error message even though it is technically a breaking change. Justification for this is that accessing null pointers looks like a coding bug and developers are likely not catching NullReferenceException specifically for this and are more likely catching a general exception. 

I added one other comment for a change that we would like then I can work on getting this PR merged in.

2023-10-02 09:17 UTC, diegorafael commented on sdk/src/Services/DynamoDBv2/Custom/DocumentModel/DynamoDBEntry.cs
> +            return p?.AsString();
Fair enough. Done.

2023-10-04 04:53 UTC, 96malhar commented
@diegorafael The PR looks good. Can you rebase your changes on the latest `master`? Once that is done we'd be happy to approve it and take it through our internal release process.

2023-10-04 16:00 UTC, 96malhar requested changes

2023-10-04 16:00 UTC, 96malhar commented on sdk/src/Services/DynamoDBv2/DynamoDBv2.sln
>  Microsoft Visual Studio Solution File, Format Version 12.00
The `.sln` file is generated via our SDK generators so any manual changes made on this will not persist. Can you remove the changes to this file?

2023-12-27 19:07 UTC, dscpinheiro commented
Closing this PR, feel free to re-open if you intend to address the feedback left previously.

2023-12-27 19:07 UTC, closed without merging