Ghi2503 add nongeneric saveasync to dynamodbcontext
aws/aws-sdk-net pull request #2504
Opened 2022-12-20 22:13 UTC by ericjpeters

## Description
Added a non-generic SaveAsync call to DynamoDBContext.   This makes usage of the DynamoDBContext possible when the generic T in SaveAsync<T> is not known at compile-time.

## Motivation and Context
Addresses feature request #2503 
https://github.com/aws/aws-sdk-net/issues/2503

## Testing
Still working on testing.  Having trouble getting the master branch to build the test project - I'm sure it's me.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-01-27 17:48 UTC, normj requested changes

2023-01-27 20:51 UTC, ericjpeters commented on sdk/src/Services/DynamoDBv2/Custom/DataModel/Context.cs
> +        private async Task SaveHelperAsync(Type valueType, object value, DynamoDBOperationConfig operationConfig, CancellationToken cancellationToken)
Ugh, not sure how I missed that!  Fixed.

2023-06-12 19:00 UTC, muhammad-othman commented
@ericjpeters Do we still need this PR? I believe all the changes were added to #2506

2023-06-12 19:38 UTC, dscpinheiro commented
Thanks for confirming it. We'll close this PR but merge the other one once it's approved and tested.

2023-06-12 19:38 UTC, closed without merging