NETCore.Setup: Add null-check on options in CreateServiceClient.
aws/aws-sdk-net pull request #2539
Opened 2023-02-14 01:47 UTC by adeutscher

Add a null-check to options in CreateServiceClient

## Description

The check for `SessionRoleArn` in `ClientFactory.CreateServiceClient` assumes that options have been initialized during dependency injection setup. If this is not the case, then a NullReferenceException is thrown upwards.

Added a monadic null-check to make the method safe for nulls.

## Motivation and Context

Resolves a breaking change introduced between `3.7.23 and `3.7.3`

## Testing

* Added a unit test that shall fail if the change to `ClientFactory.CreateServiceClient` is not present.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-02-14 07:15 UTC, normj approved these changes

2023-02-14 07:36 UTC, adeutscher commented
@normj I just realized an issue with my new test case.

Everything ran fine on my setup with some AWS configuration, but when I ran the tests cold in a fresh environment I got an error because the test couldn't tell which region to pick.

Since the point of this test was to test default behavior without setting up a configuration, I think that I have two options:

* Drop the test because it needs external setup to run cleanly.
* Within the new test, set the `AWS_REGION` environment variable. I've had unit tests that mess with environment variables step on each other's toes in the past, so I'd like to confirm with you if you think that this will make tests inconsistent and disqualify this option.

Is there an alternative that I'm not considering?

2023-02-14 08:06 UTC, adeutscher commented
@normj Uploaded a commit that opts for setting an environment variable. Reflecting on it, I think the situation from the past that I was thinking of was more "outside-IDE variables interfering with environment-variable-sensitive tests" than "environment variables from within the test setup interfering with each other".

If that read sounds off-kilter, then just ignoring the new test when this gets translated to a commit may be the way to go.

2023-02-14 15:33 UTC, adeutscher commented
@normj Sleeping on it, in all my talks of consistency worries I forgot to actually double-check how other tests in the codebase work with unit tests.

Other tests within unit tests also set environment variables, and I was just being jumpy because of inconsistent tests that I've written in the past for another project.

2023-02-14 17:36 UTC, boblodgett requested changes

2023-02-14 18:24 UTC, adeutscher commented on extensions/test/NETCore.SetupTests/DependencyInjectionTests.cs
> +            Environment.SetEnvironmentVariable("AWS_REGION", "us-east-1");
Uploaded a commit that saves the original value and restores it.

2023-02-14 18:27 UTC, boblodgett approved these changes

2023-02-14 23:45 UTC, merged

2023-02-15 00:20 UTC, normj commented
The PR is released as part of version [3.7.4](https://www.nuget.org/packages/AWSSDK.Extensions.NETCore.Setup/3.7.4). Thanks for the PR!