feat: Add support for retrieving DateTime attributes in UTC timezone from a DynamoDB table
aws/aws-sdk-net pull request #3098
Opened 2023-11-10 05:52 UTC by 96malhar

## Description
This PR adds support for retrieving `DateTime` attributes in UTC timezone from a DynamoDB table.

While working in the data model mode, this PR introduces a boolean flag called `RetrieveDateTimeInUtc` as part of the `DynamoDBContextConfig` as well as the global `AWSConfigsDynamoDB.Context`. If set to `true`, then all `DateTime` attributes are retrieved in the UTC timezone.

While working in the document model mode, Each `Document` object stores attributes as a `DynamoDBEntry`. The SDK already has the `AsDateTime` virtual method that is used to convert a `DynamoDBEntry` to a `DateTime` object. This PR also introduces a `AsDateTimeUtc` method to retrieve all `DateTime` attributes in the UTC timezone.

## Motivation and Context

Fixes https://github.com/aws/aws-sdk-net/issues/1450 and DOTNET-7259

## Testing

Added new unit and integration tests. Pending a dry-run

## Screenshots (if appropriate)

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [x] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2023-11-15 22:40 UTC, normj requested changes

2023-11-15 22:40 UTC, normj commented on sdk/src/Services/DynamoDBv2/Custom/AWSConfigs.DynamoDB.cs
> +        /// If true, all <see cref="DateTime"/> properties are retrieved in UTC timezone while reading data from DynamoDB. Else, the local timezone is used.
Can you make this clear this is for the high level library. The service client itself is going to always use UTC.

2023-11-15 22:40 UTC, normj commented on sdk/src/Services/DynamoDBv2/Custom/DataModel/Configs.cs
> +        /// If true, all <see cref="DateTime"/> properties are retrieved in UTC timezone while reading data from DynamoDB. Else, the local timezone is used.
Can you make this clear this is for the high level library. The service client itself is going to always use UTC.

2023-11-15 23:37 UTC, ashovlin commented on sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs
> +                if (targetType == typeof(DateTime) && flatConfig.RetrieveDateTimeInUtc)
Can a user register their own `DateTime` converter? Wonder if we should only do this if it's the built-in one vs. something custom.

2023-11-16 07:19 UTC, normj approved these changes

2023-11-16 07:19 UTC, normj approved these changes

2023-11-16 15:55 UTC, ashovlin commented on sdk/src/Services/DynamoDBv2/Custom/DataModel/ContextInternal.cs
> +                if (targetType == typeof(DateTime) && flatConfig.RetrieveDateTimeInUtc)
Thanks, I didn't realize a custom converter isn't getting this far.

2023-11-16 15:56 UTC, ashovlin approved these changes

2023-11-16 17:38 UTC, merged