Change extension projects version strategy in V4 to set AssemblyVersion.
aws/aws-sdk-net pull request #3341
Opened 2024-06-10 22:34 UTC by boblodgett

## Description

This PR builds on the generator change PR of the same type here: https://github.com/aws/aws-sdk-net/pull/3335

The extensions based projects do not go through the generator and must be manually set. There is no BCL typedef. Instead NETFRAMEWORK is used as is specified here: https://learn.microsoft.com/en-us/dotnet/core/tutorials/libraries#preprocessor-symbols

## Testing

Built AWSSDK.Extensions.sln and ran all tests within the solution. All pass.

## Screenshots (if appropriate)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2024-06-11 04:06 UTC, normj requested changes

2024-06-11 04:06 UTC, normj commented on extensions/src/AWSSDK.Extensions.NETCore.Setup/Properties/AssemblyInfo.cs
> +#if NETFRAMEWORK
AWSSDK.Extenstions.NETCore.Setup doesn't have any .NET Framework targets so you can get rid of the `#if` and just always set the `AssemblyVersion` to the same as `AssemblyFileVersion`.

2024-06-13 06:27 UTC, normj approved these changes

2024-06-14 13:21 UTC, dscpinheiro approved these changes

2024-06-14 17:30 UTC, merged