Generator implementation for V2 smoke tests for C2J files.
aws/aws-sdk-net pull request #3578
Opened 2024-12-12 18:11 UTC by AlexDaines

## Description
Implements the generator for smoke tests v2 format based on the new smoke-2.json schema. Key features:

- Supports all configuration options from the smoke-2.json schema
- Handles complex input types including arrays and nested objects
- Generates both success and failure test cases
- Includes proper test categorization
- Manages special cases for Tags and Includes objects

Questions for review:
1. Special case handling for Tags/Includes - should this be more generic?
2. Configuration defaults - should we explicitly set schema defaults?
3. Error handling - any additional checks needed beyond ErrorCode?
4. Input validation - should we validate against operation parameters?
5. Test categorization - any additional AWS-specific categories needed?

## Motivation and Context
This implementation supports the new smoke tests format (smoke-2.json) which provides more configuration options and better structure for test cases. The generator creates test files that:
- Allow per-test configuration
- Support all endpoint configuration options
- Handle complex input structures
- Provide proper error handling and validation

## Testing
- Verified generation with ACM service model
- Tested various scenarios including:
  - Success and failure cases
  - Complex input structures (arrays, nested objects)
  - Special cases (Tags, Includes)
  - Edge cases (null values, empty strings)
  - All configuration options
- Generated tests compile successfully

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/aws/aws-sdk-net/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

2024-12-13 08:02 UTC, normj requested changes

2024-12-17 23:44 UTC, dscpinheiro commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
>  using Microsoft.VisualStudio.TestTools.UnitTesting;
(I'm not reviewing the PR, but...) Is there a reason why you're using MSTest as the test framework? 

The [hand-written files](https://github.com/aws/aws-sdk-net/blob/main/sdk/test/Services/SecretsManager/SmokeTests/SmokeTest.cs) we have right now use xUnit (meaning they can run in parallel) and using xUnit will allow you to test your PR without making any changes to our build system (as long as they're found by the projects in this folder: https://github.com/aws/aws-sdk-net/tree/v4-development/sdk/test/SmokeTests).

2025-01-05 22:38 UTC, AlexDaines commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
> +            request.<#=key#> = "<#=value.ToString()#>";
Now using FindPropertyName, which should handles cases where the JSON key name doesn't exactly match the .NET property name.

2025-01-05 22:42 UTC, AlexDaines commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
> +                Assert.AreEqual("<#=errorId#>", ex.ErrorCode);
Null check for this added

2025-01-05 22:46 UTC, AlexDaines commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
>  using Microsoft.VisualStudio.TestTools.UnitTesting;
@normj

2025-01-08 01:27 UTC, peterrsongg commented
I tried running the generator and it seems like this needs to be changed as well

```
            if (this.Configuration.ServiceModel.HasSmokeTestsV2)
            {
                ExecuteIntegrationTestGenerator(new SmokeTestsV2(), "SmokeTestsV2.cs");
            }
```

with this logic, each file will be `SmokeTestsV2.cs` and one will overwrite the other. You should probably do something similar to the other generators and do something like

```
ExecuteIntegrationTestGenerator(new SmokeTestsV2(), serviceName + "SmokeTestsV2.cs");
```

2025-01-08 02:02 UTC, peterrsongg commented
^^ looking into the problem I mentioned above a bit more, it seems like it thinks these generated integ tests are orphaned files because they are not a part of the `generatedTestFiles` that get populated here
https://github.com/aws/aws-sdk-net/blob/main/generator/ServiceClientGenerator/Program.cs#L64-L79

since it is not part of that list, when it is passed into `GeneratorDriver.RemoveOrphanedShapesAndServices` it gets removed. This is probably the first instance of a generated integ tests so you should add these generated integ tests to the list so it isn't removed

2025-01-08 23:07 UTC, peterrsongg requested changes

2025-01-08 23:07 UTC, peterrsongg commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
> +            var response = await serviceClient.<#=modeledOperation.Name#>Async(request);
Add `.ConfigureAwait(false)` at the end of this async call. We should always be adding that at the end of async calls, unless you really know what you're doing. See https://devblogs.microsoft.com/dotnet/configureawait-faq/#why-would-i-want-to-use-configureawait(false) for why we should use `configureAwait(false)`

2025-01-08 23:07 UTC, peterrsongg commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
> +                var response = await serviceClient.<#=modeledOperation.Name#>Async(request);
same comment as above

2025-01-08 23:07 UTC, peterrsongg commented on generator/ServiceClientGeneratorLib/Generators/TestFiles/SmokeTestsV2.tt
>  using Microsoft.VisualStudio.TestTools.UnitTesting;
unless you want to make a buildsystem change I'd probably listen to daniel here

2025-03-26 17:03 UTC, dscpinheiro commented
Closing as the smoke tests work is on hold. Will revisit this later.

2025-03-26 17:03 UTC, closed without merging